#!/usr/bin/env bash
# Bash script that displays"To infinity and beyond indefinitely"
function sigterm_handler() {
    echo "I am invincible!!!"
    exit 0
}

# Register the SIGTERM handler
trap 'sigterm_handler' SIGTERM

while true; do
    echo "To infinity and beyond indefinitely"
    sleep 2
done
